sudo: false
language: node_js

addons:
  sonarcloud:
    organization: "swissquote"
    branches:
      - master

cache:
#  yarn: true
  directories:
#    - node_modules
    - vendor

os:
  - linux
  - osx
#  - windows

jdk:
  - oraclejdk8

node_js:
#  - '11'
  - '10'
  - '8'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

# Disable sonar-scanner in Pull Requests as it's not able find the command.
script:
  - _SILENT_JAVA_OPTIONS="$_JAVA_OPTIONS"
  - unset _JAVA_OPTIONS
  - alias java='java "$_SILENT_JAVA_OPTIONS"'
  - yarn test
  - sonar-scanner || true # Don't fail because of Sonarqube

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - os: windows
    - node: "11"

jobs:
  include:
    - stage: "Deploy Documentation"
      node_js: "8"
      script: skip
      before_deploy:
        - composer install
        - vendor/bin/daux generate --themes=docs_theme
      deploy:
        provider: pages
        local_dir: static
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        on:
          branch: master
