sudo: false
language: node_js

addons:
  sonarcloud:
    organization: "swissquote"
    branches:
      - master

cache:
  yarn: true
  directories:
    - node_modules
    - vendor

jdk:
  - oraclejdk8

node_js:
  - '9'
  - '8'
  - '6'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

# Disable sonar-scanner in Pull Requests as it's not able find the command.
script:
  - _SILENT_JAVA_OPTIONS="$_JAVA_OPTIONS"
  - unset _JAVA_OPTIONS
  - alias java='java "$_SILENT_JAVA_OPTIONS"'
  - yarn test
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then sonar-scanner; fi'

before_deploy:
  - composer install
  - vendor/bin/daux generate --themes=docs_theme

deploy:
  provider: pages
  local_dir: static
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master