sudo: false
language: node_js

addons:
  sonarcloud:
    organization: "swissquote"
    branches:
      - master

cache:
#  yarn: true
  directories:
#    - node_modules
    - vendor

os:
  - linux
  - osx
#  - windows

jdk:
  - oraclejdk8

node_js:
#  - '11'
  - '10'
  - '9'
  - '8'

# Disable Yarn PNP by default, add only one matrix entry 
env:
  - NPM_CLIENT=yarn
  - YARN_PLUGNPLAY_OVERRIDE=0 

# Make sure we have the latest Yarn version
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - $NPM_CLIENT install

# Disable sonar-scanner in Pull Requests as it's not able find the command.
script:
  - _SILENT_JAVA_OPTIONS="$_JAVA_OPTIONS"
  - unset _JAVA_OPTIONS
  - alias java='java "$_SILENT_JAVA_OPTIONS"'
  - $NPM_CLIENT test
  - sonar-scanner || true # Don't fail because of Sonarqube

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - os: windows
    - node_js: "11"
  include:
    - node_js: "10"
      env: NPM_CLIENT=npm
    - node_js: "10"
      env: YARN_PLUGNPLAY_OVERRIDE=1
    - stage: "Deploy Documentation"
      node_js: "10"
      script: skip
      before_deploy:
        - composer install
        - vendor/bin/daux generate --themes=docs_theme
      deploy:
        provider: pages
        local_dir: static
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        on:
          branch: master
