sudo: false
language: node_js
cache:
  directories:
  - node_modules

jdk:
  - oraclejdk8

node_js:
  - '8'
  - '6'
  - '4'

install:
  - npm install
  - npm run bootstrap

script:
  - _SILENT_JAVA_OPTIONS="$_JAVA_OPTIONS"
  - unset _JAVA_OPTIONS
  - alias java='java "$_SILENT_JAVA_OPTIONS"'
  - npm run test

after_script:
  - composer install
  - vendor/bin/daux generate

deploy:
  provider: pages
  local_dir: static
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master